#!/usr/bin/env python

import argparse
import re

from postfix_forward import *

parser = argparse.ArgumentParser()
parser.add_argument('address', nargs='+')
parser.add_argument('--user', '-u')

parser.set_defaults(
	user = None,
	password = None,
	db = 'mysql',
)

args = parser.parse_args()

if args.db == 'mysql':
	db = mysql_editor(user=args.user, passwd=args.password)
for address in args.address:
	if not re.match('[a-z_+.-]+@[a-z_+.-]+', address):
		raise ValueError('Expected email address: %s' % address)
	user,domain=address.partition('@')[::2]
	db.delete('aliases', user=user, domain=domain)
