#!/usr/bin/env python

import argparse
import re

from postfix_forward import *

parser = argparse.ArgumentParser()
parser.add_argument('orig', nargs='+')
parser.add_argument('address')
parser.add_argument('--user', '-u')
parser.set_defaults(
	user = None,
	password = None,
	db = 'mysql',
)
args = parser.parse_args()

for address in args.orig:
	if not re.match('[a-z_+.@-]', address):
		raise ValueError('Expected email address: %s' % address)
if not re.match('[a-z_+.@-]', args.address):
	raise ValueError('Expected email address: %s' % args.goto)

if args.db == 'mysql':
	db = mysql_editor(user=args.user, passwd=args.password)
with db:
	for address in args.orig:
		user,_,domain = address.partition('@')
		db.aliases.insert(name=name, domain=domain, address=args.address)
